language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install: composer install
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 --colors -n src